services:
  mariadb:
    build: 
      context: /home/emagueri/inception/srcs/requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - /home/emagueri/inception/srcs/.env
    volumes:
      - DB:/var/lib/mysql
    networks:
      - my_network
      
  wordpress:
    build: 
      context: /home/emagueri/inception/srcs/requirements/wordpress
    container_name: wordpress
    
    ports:
      - "9000:9000"
    env_file:
      - /home/emagueri/inception/srcs/.env
    volumes:
      - WordPress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - my_network

  nginx:
    build:
      context: /home/emagueri/inception/srcs/requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - /home/emagueri/inception/srcs/.env
    volumes:
      - WordPress:/var/www/wordpress
    depends_on:
      - mariadb
      - wordpress
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
volumes:
  DB:
  WordPress: