services:
  nginx:
    restart: always
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - WORDPRESS_VOLUME:/var/www/wordpress
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inception_network

  mariadb:
    build: 
      context: ./requirements/mariadb
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - DATABASE_VOLUME:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_pass
      
  wordpress:
    build: 
      context: ./requirements/wordpress
    restart: always
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    volumes:
      - WORDPRESS_VOLUME:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    secrets:
      - db_pass
      - wp_admin_pass
      - wp_user_pass
      - ftp_pass
      - redis_pass


  redis:
    build:
      context: ./requirements/bonus/redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - WORDPRESS_VOLUME:/var/www/wordpress
    depends_on:
      - wordpress
    env_file:
      - ./.env
    networks:
      - inception_network
    secrets:
      - redis_pass
  
  ftp:
    build:
      context: ./requirements/bonus/ftp
    restart: always
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "40000-40100:40000-40100"
    depends_on:
      - wordpress
    env_file:
      - ./.env
    volumes:
      - WORDPRESS_VOLUME:/home/ftpuser
    networks:
      - inception_network
    secrets:
      - ftp_pass

  adminer:
    build:
      context: ./requirements/bonus/adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - inception_network
  
  website:
    build:
      context: ./requirements/bonus/website
    container_name: website
    ports:
      - "3030:3030"
    env_file:
      - ./.env
  
  cadvisor:
    build:
      context: ./requirements/bonus/cadvisor
    container_name: cadvisor
    ports:
      - "3131:3131"
    env_file:
      - ./.env
  

secrets:
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
  wp_user_pass:
    file: ../secrets/wp_user_pass
  db_pass:
    file: ../secrets/db_pass
  ftp_pass:
    file: ../secrets/ftp_pass
  redis_pass:
    file: ../secrets/redis_pass

networks:
  inception_network:
    driver: bridge
volumes:
  DATABASE_VOLUME:
    driver: local
    driver_opts:
      type: none
      device: ~/data/database
      o: bind
  WORDPRESS_VOLUME:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind